apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  MONGODB_URI: "mongodb://mongodb-service:27017"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  USER_SERVICE_URL: "http://user-service:8081"
  PRODUCT_SERVICE_URL: "http://product-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  JWT_SECRET: ZEdocGN5QnBjeUJoSUhabGNua2diRzl1WnlCelpXTnlaWFFnYTJWNUlHWnZjaUJxZDNRZ2RHOXJaVzRnWjJWdVpYSmhkR2x2YmlCaGJtUWdkbUZzYVdSaGRHbHZiZz09
  MONGODB_PASSWORD: YWRtaW4xMjM=
